/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.taetech.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jw
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        linuxlogo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        MenCadUsua = new javax.swing.JMenuItem();
        MenCadEquip = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menRelat = new javax.swing.JMenu();
        MenRelatvisual = new javax.swing.JMenuItem();
        MenRelatRuido = new javax.swing.JMenuItem();
        MenAjuda = new javax.swing.JMenu();
        MenAJudaSob = new javax.swing.JMenuItem();
        menAjudaSoft = new javax.swing.JMenuItem();
        MenOpc = new javax.swing.JMenu();
        MenOpcSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taetech System Analysis");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        linuxlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/taetech/icones/linux2.png"))); // NOI18N

        lblusuario.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblusuario.setText("Usuário");

        lbldata.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lbldata.setText("Data");

        menCad.setText("Cadastro");

        MenCadUsua.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        MenCadUsua.setText("Usuários");
        MenCadUsua.setEnabled(false);
        MenCadUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadUsuaActionPerformed(evt);
            }
        });
        menCad.add(MenCadUsua);

        MenCadEquip.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        MenCadEquip.setText("Equip. VIsual");
        MenCadEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadEquipActionPerformed(evt);
            }
        });
        menCad.add(MenCadEquip);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Equip. Ruido");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menCad.add(jMenuItem1);

        Menu.add(menCad);

        menRelat.setText("Relatório");

        MenRelatvisual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        MenRelatvisual.setText("Visuais");
        MenRelatvisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenRelatvisualActionPerformed(evt);
            }
        });
        menRelat.add(MenRelatvisual);

        MenRelatRuido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        MenRelatRuido.setText("Ruidos");
        MenRelatRuido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenRelatRuidoActionPerformed(evt);
            }
        });
        menRelat.add(MenRelatRuido);

        Menu.add(menRelat);

        MenAjuda.setText("Ajuda");

        MenAJudaSob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenAJudaSob.setText("Sobre Min");
        MenAJudaSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAJudaSobActionPerformed(evt);
            }
        });
        MenAjuda.add(MenAJudaSob);

        menAjudaSoft.setText("Software");
        menAjudaSoft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAjudaSoftActionPerformed(evt);
            }
        });
        MenAjuda.add(menAjudaSoft);

        Menu.add(MenAjuda);

        MenOpc.setText("Opções");

        MenOpcSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenOpcSair.setText("Sair");
        MenOpcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcSairActionPerformed(evt);
            }
        });
        MenOpc.add(MenOpcSair);

        Menu.add(MenOpc);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(linuxlogo)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(linuxlogo)
                .addContainerGap())
            .addComponent(Desktop)
        );

        setSize(new java.awt.Dimension(765, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void MenRelatRuidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenRelatRuidoActionPerformed
        TelaRelatRuidos relatruido = new TelaRelatRuidos();
        relatruido.setVisible(true);
        Desktop.add(relatruido);
        
       
    }//GEN-LAST:event_MenRelatRuidoActionPerformed
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lbldata.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MenOpcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair?","Atenção",JOptionPane.YES_NO_OPTION);
        if (sair ==  JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_MenOpcSairActionPerformed

    private void MenAJudaSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAJudaSobActionPerformed
        // TODO add your handling code here:
        try {
            String URL = "http://henzelcurriculum.herokuapp.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_MenAJudaSobActionPerformed

    private void menAjudaSoftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAjudaSoftActionPerformed
        // TODO add your handling code here:
        telaSoftware software = new telaSoftware();
        software.setVisible(true);
    }//GEN-LAST:event_menAjudaSoftActionPerformed

    private void MenCadUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadUsuaActionPerformed
        // TODO add your handling code here:
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        Desktop.add(usuario);
    }//GEN-LAST:event_MenCadUsuaActionPerformed

    private void MenCadEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadEquipActionPerformed
        // TODO add your handling code here:
        TelaEquipamentos equipamentos = new TelaEquipamentos();
        equipamentos.setVisible(true);
        Desktop.add(equipamentos);
        
    }//GEN-LAST:event_MenCadEquipActionPerformed

    private void MenRelatvisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenRelatvisualActionPerformed
        // TODO add your handling code here:
        TelaRelatVisual relatvisual = new TelaRelatVisual();
        relatvisual.setVisible(true);
        Desktop.add(relatvisual);
        
       
    }//GEN-LAST:event_MenRelatvisualActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaEquipRuidos equipruidos = new TelaEquipRuidos();
        equipruidos.setVisible(true);
        Desktop.add(equipruidos);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem MenAJudaSob;
    private javax.swing.JMenu MenAjuda;
    private javax.swing.JMenuItem MenCadEquip;
    public static javax.swing.JMenuItem MenCadUsua;
    private javax.swing.JMenu MenOpc;
    private javax.swing.JMenuItem MenOpcSair;
    private javax.swing.JMenuItem MenRelatRuido;
    private javax.swing.JMenuItem MenRelatvisual;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbldata;
    public static javax.swing.JLabel lblusuario;
    private javax.swing.JLabel linuxlogo;
    private javax.swing.JMenuItem menAjudaSoft;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenu menRelat;
    // End of variables declaration//GEN-END:variables
}
